# Generated by Django 4.2 on 2025-03-03 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(db_column='BatchID', primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_column='BatchNo', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 46281, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 46305, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(db_column='LevelID', primary_key=True, serialize=False)),
                ('level_no', models.CharField(db_column='LevelNo', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 46669, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 46683, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(db_column='ParticipantID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('primary_skill', models.CharField(db_column='PrimarySkill', max_length=255, null=True)),
                ('secondary_skill', models.CharField(db_column='SecondrySkill', max_length=255, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=255, null=True)),
                ('stepup_started', models.DateTimeField(db_column='StepUp_Started', null=True)),
                ('delivery_unit', models.IntegerField(db_column='DU', null=True)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255, null=True)),
                ('emp_id', models.CharField(db_column='EmployeeId', max_length=255, null=True)),
                ('total_exp', models.IntegerField(db_column='TotalExperience', null=True)),
                ('skill', models.CharField(db_column='Skills', max_length=255, null=True)),
                ('designation', models.CharField(db_column='Designation', max_length=255, null=True)),
                ('project_involvement', models.CharField(db_column='Involvement', max_length=255, null=True)),
                ('invited_for_next_lvl', models.BooleanField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('is_delete', models.BooleanField(null=True)),
                ('comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 47897, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 47910, tzinfo=datetime.timezone.utc))),
                ('batch', models.ForeignKey(blank=True, db_column='BatchID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stepup_api.batch')),
                ('latest_level_passed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stepup_api.level')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_column='SubjectName', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 47022, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 47036, tzinfo=datetime.timezone.utc))),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stepup_api.level')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='uploaded_sheets/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stepup_api.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(db_column='TestResultID', primary_key=True, serialize=False)),
                ('attempt', models.IntegerField(db_column='NumberOfAttempts', null=True)),
                ('invite_time', models.DateTimeField(db_column='InviteTime')),
                ('test_status', models.CharField(db_column='TestStatus', max_length=255, null=True)),
                ('submitted_date', models.DateTimeField(db_column='SubmittedDate', null=True)),
                ('cn_rating', models.FloatField(db_column='CNRating', null=True)),
                ('appeared_in_test', models.IntegerField(db_column='AppearedInTest', null=True)),
                ('submitted_reason', models.CharField(db_column='SubmittedReason', max_length=255, null=True)),
                ('test_name', models.CharField(db_column='TestName', max_length=255, null=True)),
                ('no_of_attempts_invited', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 48584, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 56, 48596, tzinfo=datetime.timezone.utc))),
                ('batch', models.ForeignKey(db_column='BatchID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.batch')),
                ('level', models.ForeignKey(db_column='LevelID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.level')),
                ('participant', models.ForeignKey(db_column='ParticipantID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.participant')),
                ('subject', models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.subject')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
    ]
