# Generated by Django 4.2 on 2025-02-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.AutoField(db_column='AttemptID', primary_key=True, serialize=False)),
                ('attempt_no', models.CharField(db_column='AttemptNo', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'attempts',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(db_column='BatchID', primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_column='BatchNo', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(db_column='LevelID', primary_key=True, serialize=False)),
                ('level_no', models.CharField(db_column='LevelNo', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(db_column='ParticipantID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('primary_skill', models.CharField(db_column='PrimarySkill', max_length=255, null=True)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_column='SubjectName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(db_column='TestResultID', primary_key=True, serialize=False)),
                ('invite_time', models.DateTimeField(db_column='InviteTime')),
                ('test_status', models.CharField(db_column='TestStatus', max_length=255, null=True)),
                ('submitted_date', models.DateTimeField(db_column='SubmittedDate', null=True)),
                ('cn_rating', models.FloatField(db_column='CNRating', null=True)),
                ('appeared_in_test', models.BooleanField(db_column='AppearedInTest', null=True)),
                ('submitted_reason', models.CharField(max_length=255, null=True)),
                ('test_name', models.CharField(max_length=255)),
                ('attempt', models.ForeignKey(db_column='AttemptID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.attempt')),
                ('batch', models.ForeignKey(db_column='BatchID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.batch')),
                ('level', models.ForeignKey(db_column='LevelID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.level')),
                ('participant', models.ForeignKey(db_column='ParticipantID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.participant')),
                ('subject', models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, to='stepup_api.subject')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
    ]
