# Generated by Django 4.2 on 2025-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='appeared_in_test',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
