# Generated by Django 4.2 on 2025-03-13 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 97517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 97541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='level',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 97906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='level',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 97922, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 99186, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 99199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 98289, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 98304, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 99882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 16, 5, 99895, tzinfo=datetime.timezone.utc)),
        ),
    ]
