# Generated by Django 4.2 on 2025-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='appeared_in_test',
            field=models.CharField(max_length=3),
        ),
    ]
