# Generated by Django 4.2 on 2025-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0002_alter_testresult_appeared_in_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='appeared_in_test',
            field=models.BooleanField(db_column='AppearedInTest', null=True),
        ),
    ]
