# Generated by Django 4.2 on 2025-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0003_alter_testresult_appeared_in_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='submitted_reason',
            field=models.CharField(db_column='SubmittedReason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(db_column='TestName', max_length=255),
        ),
    ]
