# Generated by Django 4.2 on 2025-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cn_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='primary_skill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='submitted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='test_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
