# Generated by Django 4.2 on 2025-02-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepup_api', '0006_participant_cn_rating_participant_primary_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_time', models.DateTimeField()),
                ('test_status', models.CharField(max_length=255, null=True)),
                ('submitted_date', models.DateTimeField(null=True)),
                ('cn_rating', models.FloatField(null=True)),
                ('appeared_in_test', models.CharField(max_length=3)),
                ('submitted_reason', models.CharField(max_length=255, null=True)),
                ('test_name', models.CharField(max_length=255)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepup_api.attempt')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepup_api.batch')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepup_api.level')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='appeared_in_test',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='cn_rating',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='invite_time',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='submitted_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='submitted_reason',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='test_status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='participant',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='primary_skill',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='participant',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='testresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepup_api.participant'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepup_api.subject'),
        ),
    ]
